# Abstract {#abstract}

Snow packs store valuable water resources, influence global climate dynamics, and provide outdoor recreational opportunities, but the spatial and temporal distribution of snow pack properties are hard to quantify and are sensitive to climate change. Remotely sensed data can provide valuable large scale information about snow in hard to access locations, but technical expertise can be a barrier to extracting meaningful insights. Scientists at the UCSB Earth Research Institute help communicate remotely sensed snow conditions through the Snow Today website, which presents daily images and monthly blog posts on the status of snow, including snow cover percent and albedo. The data used to generate these insights are available on the website, but since the data processing and visualization was completed with Matlab, a proprietary computational software system, the workflow does not follow open source data practices. Our project addresses these limitations by creating an open source workflow that improves the usability of snow data through interactive web based visualizations and Python based tutorials. These contributions will also help guide the design of updates to the user experience and interface of the Snow Today website. Now water managers, scientists, and recreationalist can complete customized analyses of snow data for specific regions of interest to support planning and decision making for water supply allocation, hydrologic research, and recreational planning. As the impacts of climate change continue to affect snow conditions, the improved usability of Snow Today’s datasets is important for informing snow resource planning and decision making.
