# Abstract {-}

Snowpacks store valuable water resources, influence global climate dynamics, and provide outdoor recreational opportunities. The spatial and temporal distribution of its properties are hard to quantify and are sensitive to climate change. Remotely sensed snow data provides valuable information, but technical expertise can be a barrier to extracting meaningful insights from this data. Scientists at the University of California, Santa Barbara Earth Research Institute help communicate remotely sensed snow conditions through the Snow Today website, which presents daily images and monthly updates of snow variables, such as albedo. The data used to generate these insights are available on the website, but since the analysis is completed with Matlab, a proprietary computational software system, the workflow does not follow open-source data practices. Our Project addresses these limitations by creating an open-source workflow that improves the usability of snow data through interactive web-based visualizations and Python-based tutorials. As the impacts of climate change continue to affect snow conditions, the improved usability of Snow Today’s datasets allows for customized analyses of snow data for specific regions of interest to support decision making for water supply allocation, hydrologic research, and recreational planning.
