# Executive Summary {-}

Snow is one of the most important natural water resources present in nature. It stores water in winter and releases it in spring during the melting season. Snow also influences the Earth’s ability to regulate its temperature [@newton2021]. Knowing the spatial extent of snow cover and understanding its properties is critical for water resource management and modeling global climatic conditions [@liston1999].

Snow data collection includes snow cover extent and albedo percentages. Albedo measures how much solar radiation is reflected from a surface. Obtaining accurate information on snow coverage and albedo data is critical to modeling and analyzing water resource availability. Estimating snow cover variability and spatial extent is essential for proactive water management, and monitoring snow cover is important for planning and facilitating winter recreation activities. For these reasons, a centralized repository of snow data accessible to water managers and scientists is essential.

The Snow Today website is a leading source of seasonal snow condition data products for environmental remote sensing and field observations. The site’s intended audience includes scientists, water resource managers, and recreationalists who access up-to-date information on the state of snowpack properties from the watershed basin to the regional level across the Western United States. Spatial products offered by Snow Today include snow-covered areas, snow cover days, albedo percentages, and snow water equivalent (SWE). Snow Today is currently expanding its spatial domain from the Western United States to all of North America, Greenland, and High Mountain Asia. The researchers at Snow Today are taking this opportunity to increase the usability and accessibility of their website to try and reach a wider audience of users. In support of these updates, affiliates of Snow Today, including researchers from the [UC Santa Barbara Earth Research Institute (ERI)](https://www.eri.ucsb.edu/) and [the University of Colorado Boulder Institute of Arctic & Alpine Research (INSTAAR)](https://instaar.colorado.edu/) (the Client), have requested the Bren Masters of Environmental Data Science Snow Today Group (the Group) to recommend how to incorporate these changes. Integration of these changes will assist Snow Today with increasing the usability and accessibility of the website in hopes of reaching a broader audience of the scientific, water management, and recreational communities. 

The Snow Today Capstone Project (Project) delivers recommendations to update the current Snow Today website by creating an information architecture plan, wireframe mockups, a web application prototype with interactive visualizations, and end-user tutorials that run in Python. The information architecture plans and wireframe mockup suggestions will help make the existing website interface easier to navigate for site users. Updating the current static visualizations with interactive visuals will increase the website’s value by allowing users to customize and compare temporal ranges. End-user tutorials will help users access, process, and visualize the complex structure of Snow Today’s snow cover and albedo datasets. These elements will help the Client achieve their goals of increasing the usability and accessibility of an updated Snow Today website to reach a wider audience and enable a larger set of users to access and interpret seasonal snow condition data.

Interactive visualizations serve as a template to replace the existing static models currently displayed on the Snow Today website. The interactive maps and charts are presented in an R Shiny application that allows users to select a specific date and view snow cover and albedo maps, then zoom in/out on the maps to view specific areas. The Shiny app also displays annual and monthly snow cover, albedo averages, and anomalies. Users can use this app to learn more about snow science, the importance of albedo, nuances of the snow and albedo metadata, and background information on the Capstone Project and Group members from supplemental tabs within the Shiny app. The “Tutorials” tab on the Shiny app directs users to notebooks on our Group Github repository.
