# Problem Statement {#background}

## Project Background

[Snow Today](https://nsidc.org/reports/snow-today) is a scientific analysis website that provides data on snow conditions using satellite data and surface observations in the Western Region of the United States. Snow Today comprises researchers from ERI, INSTAAR, Oregon State University, and the National Snow and Ice Data Center (NSIDC). The site is funded by the National Aeronautics and Space Administration (NASA) and hosted by the NSIDC.

Snow Today offers real-time data on snowpack properties from the watershed basin to the regional level across the Western United States. Spatial products offered by Snow Today include snow-covered areas, snow cover days, and albedo percentages across the Western United States. Snow Today is currently expanding its scope from the Western United States to all of North America, Greenland, and High Mountain Asia. Snow Today is taking this opportunity to explore options to expand the usability and accessibility of the website in order to reach a broader audience of scientific, water management, and recreational communities. 

## Project Significance

The Snow Today site offers valuable resources to aid snow research and track the temporal and geospatial range of snow cover and snow albedo. However, given Snow Today’s limited spatial domain, the website’s usefulness is restricted to a small group of relevant end-users interested in Western United States snow cover extent and albedo. The Client plans to expand the website’s spatial coverage from the Western United States to all of North America, Greenland, and High Mountain Asia to broaden the website’s applicability to a greater audience. Moreover, Snow Today’s existing albedo and snow cover datasets do not comply with NASA’s Hierarchical Data Format - Earth Observing System’s (HDF-EOS) metadata requirements. Geospatial software and Python packages have difficulty interpreting Snow Today’s snow-related datasets, further limiting users’ access to data and applicability. 
