# Products and Deliverables {#deliverables}

The Snow Today Group produced three deliverables to achieve the Project objective of improving the usability of snow remote sensing data:

- Created recommendations for an information architecture plan and wireframe mockups of the proposed Snow Today website;
- Developed visuals of snow cover area and albedo on an interactive website application; and 
- Generated “How To” example tutorials to guide various end users through the process of using the data to extract meaningful insights.

## Website Recommendations

Website recommendations were created to facilitate future discussions between the Clients and NSIDC web developers. These recommendations include an information architecture plan and wireframe mockup, and suggest updates to features, user selection options, pages, and aesthetics. NSIDC web developers will create the new and expanded Snow Today website informed by the Project’s recommendations. These recommendations provide a smooth user experience, present new albedo visualizations, and integrate an expanded geographic extent that includes North America, Greenland, and High Mountain Asia. Evaluating the uncertainty of the SPIReS model was outside the scope of this Project, and we suggest that the Clients include a statement quantifying the uncertainty of Snow Today products and steps taken to minimize uncertainty. 

The Project’s Snow Today website wireframe provides layout recommendations for the Snow Today website page order, content, and visualizations. The wireframe consists of six pages, which include a landing page, an about page, a page for the researchers’ monthly newsletters titled “Insights,” snow science research and data pages, and a page dedicated to tutorials. The Snow Today website landing page currently hosts the researchers’ monthly newsletter. We suggest that they update the landing page with a short introduction to Snow Today research and what is available to users on the website. Also, the landing page should host an interactive spatial visualization where a user can select a data variable, such as snow cover or albedo, select a time period or relevant date, and zoom to a particular region of interest. This visualization should populate with North America, Greenland, and High Mountain Asia data. The landing page should also link to the data and tutorial pages to facilitate ease of access to the data and how to use it. The Group recommends adding a page dedicated to snow science research, which would provide a short background on snow hydrology, snow data variables, and the Snow Today researchers’ SPIReS model [@bair2021]. This page could also host additional static or interactive snow condition data visualizations. The Project recommends expanding the current data page content by adding general information on remote sensing data and the data Snow Today researchers are creating, including relevant metadata information. The Group recommends that the Clients change the existing metadata creation process to increase the data’s geospatial interpretability. The Snow Today researchers could create a GitHub organization repository similar to this Project to facilitate ease of access to their environmental models and data processing repositories. Currently, these repositories are hosted on the researchers’ personal GitHub accounts, which are not linked on the current website. A tutorial page was added to host the Python-based tutorials created by this Project and a potential future Snow Today YouTube channel that would host additional video-based tutorials, webinars, and training. 

The current Snow Today website focuses on current snow conditions. We recommend additional features to easily allow users to view snow properties for a specific selected date or snow properties aggregated for monthly or annual timeframes. Similarly, we recommend additional spatial selection options. The current website only allows users to view the entire western US, specific states, or hydrologic unit code. We recommend that the updated Snow Today website include interactivity that allows users to zoom in and out on areas of interest. Another potentially useful feature would be a way for users to upload their own shapefiles to customize the area of interest further. For example, a water manager could be interested in viewing snow properties near specific reservoirs or for a specific watershed. 
Real-time data integration is not within the scope of this Project. However, once developed, our workflow can be incorporated into the future Snow Today website and adapted to update the interactive visuals with real-time data continuously. 

## Interactive Visualizations

Visualizations include interactive charts and maps of snow cover and albedo to display the change in these parameters over space and time. All visualizations are presented on the Snow Today Shiny application, which can be found at [https://shiny.snow.ucsb.edu/snow_today_shiny_app/](https://shiny.snow.ucsb.edu/snow_today_shiny_app/). This app is a prototype of the suggestions included in the wireframe. Currently, the Shiny app only displays data for the Sierra Nevada region from water year 2001 through water year 2019. It allows users to select any date between October 1, 2000 (water year 2001) and September 30, 2019 (water year 2019) and visualize snow cover percent and albedo on that day. Users can zoom in/out of the maps to view specific regions. In addition, users are able to visualize annual and monthly means and anomalies. The Shiny app includes documentation on snow science definitions and the data used in this Project as well as links to the tutorials discussed below.

## Tutorials

Tutorials based in Python were created to facilitate expanded use of snow cover and albedo HDF5 files from ERI’s Snow Property Inversion From Remote Sensing (SPIReS) model. The tutorials are intended to walk users through ways to comprehend and utilize the data used to make visualizations on the Snow Today website. The tutorials are for an audience with basic Python experience, but a previous understanding of multidimensional climate data is not required. The first tutorial focuses on walking users through the steps to open HDF5 files, explore metadata, and perform basic visualizations. The second tutorial provides instructions on calculating monthly and yearly means and anomalies of snow and albedo data, ways to convert data to GeoTIFF and NetCDF formats, and ways to create interactive maps. These GeoTIFF can be either individual files or raster stacks. The third tutorial focuses on calculating data statistics such as interquartile ranges and daily averages, then visualizing these values on interactive charts. While tutorials only use historic data from 2001 to 2019, the skills gained from the tutorials can be applied to present data. 
