--- 
title: "Improving Usability of Snow Data through Web-based Visualizations & Tutorials"
subtitle: "An Open Source Workflow for Processing and Visualizing Snow Data"
author: 
  - Ryan Munnikhuis | Bren School of Environmental Science & Managment | MEDS 2022
  - Julia Parish | Bren School of Environmental Science & Managment | MEDS 2022
  - Marie Rivers | Bren School of Environmental Science & Managment | MEDS 2022
date: '2022-06-03'
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [bibiliography.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: MEDSsnowtoday/Technical_Documentation
description: "MEDS Snow Today Capstone Project Technical Documentation"
---


# Signature Page

**Snow Today**

**Improving Usability of Snow Data Through Web Based Visualizations and Tutorials**

As developers of this Capstone Project documentation, we archive this documentation on the Bren School’s website such that the results of our research are available for all to read. Our signatures on the document signify our joint responsibility to fulfill the archiving standards set by the Bren School of Environmental Science & Management.

_________________________________________________
MEMBER NAME

_________________________________________________
MEMBER NAME

_________________________________________________
MEMBER NAME


The Bren School of Environmental Science & Management produces professionals with unrivaled training in environmental science and management who will devote their unique skills to the diagnosis, assessment, mitigation, prevention, and remedy of the environmental problems of today and the future. A guiding principle of the School is that the analysis of environmental problems requires quantitative training in more than one discipline and an awareness of the physical, biological, social, political, and economic consequences that arise from scientific or technological decisions.

The Capstone Project is required of all students in the Master of Environmental Data Science (MEDS) Program. The Project is a six-month-long activity in which small groups of students contribute to data science practices, products or analyses that address a challenge or need related to a specific environmental issue. 

This Capstone Project Technical Documentation is authored by MEDS students and has been reviewed and approved by:


______________________________________________
ADVISOR

______________________________________________
ADVISOR


____________________
DATE


